# Generated by Django 5.2 on 2025-07-11 16:14

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingRaport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок задачи')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок задачи')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок задачи')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок задачи')),
                ('tasks', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Задачи:')),
                ('tasks_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Задачи:')),
                ('tasks_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Задачи:')),
                ('tasks_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Задачи:')),
                ('dedline_tasks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дедлайн задачи')),
                ('dedline_tasks_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дедлайн задачи')),
                ('dedline_tasks_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дедлайн задачи')),
                ('dedline_tasks_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дедлайн задачи')),
                ('raport_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок отчета')),
                ('raport_title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок отчета')),
                ('raport_title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок отчета')),
                ('raport_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок отчета')),
                ('raport_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст отчета')),
                ('raport_text_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст отчета')),
                ('raport_text_ky', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст отчета')),
                ('raport_text_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст отчета')),
                ('document_raport', models.URLField(verbose_name='Ссылка на документ отчета')),
                ('document_raport_ru', models.URLField(null=True, verbose_name='Ссылка на документ отчета')),
                ('document_raport_ky', models.URLField(null=True, verbose_name='Ссылка на документ отчета')),
                ('document_raport_en', models.URLField(null=True, verbose_name='Ссылка на документ отчета')),
                ('file_raport', models.FileField(upload_to='media/files/', verbose_name='файл_отчета')),
            ],
            options={
                'verbose_name': 'Документ отчета',
                'verbose_name_plural': 'Документы отчетов',
            },
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentcharacteristic',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='studentcharacteristic',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='studentcharacteristic',
            name='weaknesses',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='course',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='курс студента'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='course_en',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='курс студента'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='course_ky',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='курс студента'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='course_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='курс студента'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='date_behind',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата внутри'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='date_behind_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата внутри'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='date_behind_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата внутри'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='date_behind_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата внутри'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='date_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='дата начала и конца'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='date_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='дата начала и конца'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='date_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='дата начала и конца'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='number_behind',
            field=models.IntegerField(blank=True, null=True, verbose_name='Нумерация'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='organization',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='организация - учреждение'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='organization_en',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='организация - учреждение'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='organization_ky',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='организация - учреждение'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='organization_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='организация - учреждение'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='title_behind',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Заголовок внутри'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='title_behind_en',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Заголовок внутри'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='title_behind_ky',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Заголовок внутри'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='title_behind_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Заголовок внутри'),
        ),
        migrations.AddField(
            model_name='document',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание дока'),
        ),
        migrations.AddField(
            model_name='document',
            name='content_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание дока'),
        ),
        migrations.AddField(
            model_name='document',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание дока'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок дока'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок дока'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок дока'),
        ),
        migrations.AddField(
            model_name='studentcharacteristic',
            name='title_document',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок Документы'),
        ),
        migrations.AddField(
            model_name='studentcharacteristic',
            name='title_document_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Документы'),
        ),
        migrations.AddField(
            model_name='studentcharacteristic',
            name='title_document_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Документы'),
        ),
        migrations.AddField(
            model_name='studentcharacteristic',
            name='title_document_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок Документы'),
        ),
        migrations.AddField(
            model_name='studentcharacteristic',
            name='title_filename',
            field=models.FileField(blank=True, null=True, upload_to='media/characteristik', verbose_name='Файл документа характеристики'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='avatarka',
            field=models.FileField(default=1, upload_to='media/avatarka', verbose_name='avatarka_file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='avatarka_url',
            field=models.URLField(default=1, verbose_name='avatarka_url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.IntegerField(blank=True, null=True, verbose_name='Курс на котором учиться студент'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='full_name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hash_tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хэштег студента'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hash_tag_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хэштег студента'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hash_tag_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хэштег студента'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hash_tag_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хэштег студента'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='institution_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Учреждение'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='institution_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Учреждение'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='institution_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Учреждение'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number_en',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number_ky',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='practice_day',
            field=models.CharField(blank=True, max_length=255, verbose_name='День практики'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='practice_day_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='День практики'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='practice_day_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='День практики'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='practice_day_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='День практики'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='practice_raport',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчет о практики'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='practice_raport_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчет о практики'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='practice_raport_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчет о практики'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='practice_raport_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчет о практики'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='practice_schedule',
            field=models.CharField(blank=True, max_length=255, verbose_name='Граффик практики'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='practice_schedule_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Граффик практики'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='practice_schedule_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Граффик практики'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='practice_schedule_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Граффик практики'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='special',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальность студента'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='special_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальность студента'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='special_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальность студента'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='special_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальность студента'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='дата начала и конца'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary', to='students.studentprofile'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание дока'),
        ),
        migrations.AlterField(
            model_name='document',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='students.studentprofile'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок дока'),
        ),
        migrations.AlterField(
            model_name='studentcharacteristic',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.studentprofile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PracticeInfo',
        ),
    ]
