# Generated by Django 5.2 on 2025-07-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_sendingraport_remove_diaryentry_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
    ]
