# Generated by Django 5.2 on 2025-07-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_studentprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='student',
        ),
    ]
