# Generated by Django 5.2 on 2025-07-12 11:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_document_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Содержание документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок документа'),
        ),
    ]
