# Generated by Django 5.2 on 2025-07-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_document_content_alter_document_content_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
