# Generated by Django 5.2 on 2025-07-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_delete_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ['-date'], 'verbose_name': 'Дневник', 'verbose_name_plural': 'Дневники'},
        ),
        migrations.AlterModelOptions(
            name='sendingraport',
            options={'verbose_name': 'Отправка отчёта', 'verbose_name_plural': 'Отправка отчётов'},
        ),
    ]
