# Generated by Django 5.2 on 2025-07-15 07:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_diaryentry_options_alter_sendingraport_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingraport',
            name='dedline_tasks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='sendingraport',
            name='dedline_tasks_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='sendingraport',
            name='dedline_tasks_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='sendingraport',
            name='dedline_tasks_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='sendingraport',
            name='raport_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текстовый отчет'),
        ),
        migrations.AlterField(
            model_name='sendingraport',
            name='raport_text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текстовый отчет'),
        ),
        migrations.AlterField(
            model_name='sendingraport',
            name='raport_text_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текстовый отчет'),
        ),
        migrations.AlterField(
            model_name='sendingraport',
            name='raport_text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текстовый отчет'),
        ),
        migrations.AlterField(
            model_name='sendingraport',
            name='raport_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок "Текстовый отчет"'),
        ),
        migrations.AlterField(
            model_name='sendingraport',
            name='raport_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок "Текстовый отчет"'),
        ),
        migrations.AlterField(
            model_name='sendingraport',
            name='raport_title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок "Текстовый отчет"'),
        ),
        migrations.AlterField(
            model_name='sendingraport',
            name='raport_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок "Текстовый отчет"'),
        ),
        migrations.AlterField(
            model_name='sendingraport',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок "Задачи"'),
        ),
        migrations.AlterField(
            model_name='sendingraport',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок "Задачи"'),
        ),
        migrations.AlterField(
            model_name='sendingraport',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок "Задачи"'),
        ),
        migrations.AlterField(
            model_name='sendingraport',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок "Задачи"'),
        ),
    ]
