# Generated by Django 5.2 on 2025-07-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_sendingraport_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendingRaport',
            new_name='SendingReport',
        ),
    ]
