# Generated by Django 5.2 on 2025-07-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_rename_sendingraport_sendingreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitlesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(max_length=255, verbose_name='Заголовок "Задачи"')),
                ('deadline', models.CharField(max_length=255, verbose_name='Заголовок "Дедлайн"')),
                ('report', models.CharField(max_length=255, verbose_name='Заголовок "Текстовый отчет"')),
                ('document', models.URLField(verbose_name='Заголовок "Документальный отчет"')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.RenameField(
            model_name='sendingreport',
            old_name='document_raport',
            new_name='document_report',
        ),
        migrations.RenameField(
            model_name='sendingreport',
            old_name='document_raport_en',
            new_name='document_report_en',
        ),
        migrations.RenameField(
            model_name='sendingreport',
            old_name='document_raport_ky',
            new_name='document_report_ky',
        ),
        migrations.RenameField(
            model_name='sendingreport',
            old_name='document_raport_ru',
            new_name='document_report_ru',
        ),
        migrations.RenameField(
            model_name='sendingreport',
            old_name='file_raport',
            new_name='file_report',
        ),
        migrations.RenameField(
            model_name='sendingreport',
            old_name='raport_text',
            new_name='report_text',
        ),
        migrations.RenameField(
            model_name='sendingreport',
            old_name='raport_text_en',
            new_name='report_text_en',
        ),
        migrations.RenameField(
            model_name='sendingreport',
            old_name='raport_text_ky',
            new_name='report_text_ky',
        ),
        migrations.RenameField(
            model_name='sendingreport',
            old_name='raport_text_ru',
            new_name='report_text_ru',
        ),
        migrations.RenameField(
            model_name='sendingreport',
            old_name='raport_title',
            new_name='report_title',
        ),
        migrations.RenameField(
            model_name='sendingreport',
            old_name='raport_title_en',
            new_name='report_title_en',
        ),
        migrations.RenameField(
            model_name='sendingreport',
            old_name='raport_title_ky',
            new_name='report_title_ky',
        ),
        migrations.RenameField(
            model_name='sendingreport',
            old_name='raport_title_ru',
            new_name='report_title_ru',
        ),
    ]
