# Generated by Django 5.2 on 2025-07-15 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_titlesreport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendingreport',
            name='dedline_tasks',
        ),
        migrations.RemoveField(
            model_name='sendingreport',
            name='dedline_tasks_en',
        ),
        migrations.RemoveField(
            model_name='sendingreport',
            name='dedline_tasks_ky',
        ),
        migrations.RemoveField(
            model_name='sendingreport',
            name='dedline_tasks_ru',
        ),
        migrations.RemoveField(
            model_name='sendingreport',
            name='report_title',
        ),
        migrations.RemoveField(
            model_name='sendingreport',
            name='report_title_en',
        ),
        migrations.RemoveField(
            model_name='sendingreport',
            name='report_title_ky',
        ),
        migrations.RemoveField(
            model_name='sendingreport',
            name='report_title_ru',
        ),
        migrations.RemoveField(
            model_name='sendingreport',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sendingreport',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='sendingreport',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='sendingreport',
            name='title_ru',
        ),
    ]
