# Generated by Django 5.2 on 2025-07-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_remove_sendingreport_dedline_tasks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendingreport',
            old_name='document_report',
            new_name='link_report',
        ),
        migrations.RenameField(
            model_name='sendingreport',
            old_name='document_report_en',
            new_name='link_report_en',
        ),
        migrations.RenameField(
            model_name='sendingreport',
            old_name='document_report_ky',
            new_name='link_report_ky',
        ),
        migrations.RenameField(
            model_name='sendingreport',
            old_name='document_report_ru',
            new_name='link_report_ru',
        ),
    ]
