# Generated by Django 5.2 on 2025-07-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_rename_document_report_sendingreport_link_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendingreport',
            name='link_report_en',
        ),
        migrations.RemoveField(
            model_name='sendingreport',
            name='link_report_ky',
        ),
        migrations.RemoveField(
            model_name='sendingreport',
            name='link_report_ru',
        ),
        migrations.AddField(
            model_name='titlesreport',
            name='deadline_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Дедлайн"'),
        ),
        migrations.AddField(
            model_name='titlesreport',
            name='deadline_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Дедлайн"'),
        ),
        migrations.AddField(
            model_name='titlesreport',
            name='deadline_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Дедлайн"'),
        ),
        migrations.AddField(
            model_name='titlesreport',
            name='document_en',
            field=models.URLField(null=True, verbose_name='Заголовок "Документальный отчет"'),
        ),
        migrations.AddField(
            model_name='titlesreport',
            name='document_ky',
            field=models.URLField(null=True, verbose_name='Заголовок "Документальный отчет"'),
        ),
        migrations.AddField(
            model_name='titlesreport',
            name='document_ru',
            field=models.URLField(null=True, verbose_name='Заголовок "Документальный отчет"'),
        ),
        migrations.AddField(
            model_name='titlesreport',
            name='report_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Текстовый отчет"'),
        ),
        migrations.AddField(
            model_name='titlesreport',
            name='report_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Текстовый отчет"'),
        ),
        migrations.AddField(
            model_name='titlesreport',
            name='report_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Текстовый отчет"'),
        ),
        migrations.AddField(
            model_name='titlesreport',
            name='tasks_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Задачи"'),
        ),
        migrations.AddField(
            model_name='titlesreport',
            name='tasks_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Задачи"'),
        ),
        migrations.AddField(
            model_name='titlesreport',
            name='tasks_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Задачи"'),
        ),
    ]
