# Generated by Django 5.2 on 2025-07-15 08:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_remove_sendingreport_link_report_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titlesreport',
            options={'verbose_name': 'Заголовки отчёта', 'verbose_name_plural': 'Заголовки отчётов'},
        ),
        migrations.AlterField(
            model_name='sendingreport',
            name='tasks',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='sendingreport',
            name='tasks_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='sendingreport',
            name='tasks_ky',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='sendingreport',
            name='tasks_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Задача'),
        ),
    ]
