# Generated by Django 5.2 on 2025-07-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_titlesreport_options_alter_sendingreport_tasks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_title', models.CharField(max_length=255, verbose_name='Мини заголовок')),
                ('mini_title_ru', models.CharField(max_length=255, null=True, verbose_name='Мини заголовок')),
                ('mini_title_ky', models.CharField(max_length=255, null=True, verbose_name='Мини заголовок')),
                ('mini_title_en', models.CharField(max_length=255, null=True, verbose_name='Мини заголовок')),
                ('mini_logo', models.ImageField(upload_to='media/logo', verbose_name='Мини логотип')),
                ('logo', models.ImageField(upload_to='media/logo', verbose_name='Логотип')),
                ('title_document', models.CharField(max_length=255, verbose_name='Заголовок "Документ"')),
                ('title_document_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Документ"')),
                ('title_document_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Документ"')),
                ('title_document_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Документ"')),
                ('title_documents', models.CharField(max_length=255, verbose_name='Заголовок "Документы"')),
                ('title_documents_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Документы"')),
                ('title_documents_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Документы"')),
                ('title_documents_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Документы"')),
            ],
            options={
                'verbose_name': 'Заголовок студента',
                'verbose_name_plural': 'Заголовки студентов',
            },
        ),
    ]
