# Generated by Django 5.2 on 2025-07-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_studenttitles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitlesReport',
        ),
        migrations.AddField(
            model_name='studenttitles',
            name='deadline',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок "Дедлайн"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenttitles',
            name='deadline_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Дедлайн"'),
        ),
        migrations.AddField(
            model_name='studenttitles',
            name='deadline_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Дедлайн"'),
        ),
        migrations.AddField(
            model_name='studenttitles',
            name='deadline_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Дедлайн"'),
        ),
        migrations.AddField(
            model_name='studenttitles',
            name='document_report',
            field=models.URLField(default=1, verbose_name='Заголовок "Документальный отчет"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenttitles',
            name='document_report_en',
            field=models.URLField(null=True, verbose_name='Заголовок "Документальный отчет"'),
        ),
        migrations.AddField(
            model_name='studenttitles',
            name='document_report_ky',
            field=models.URLField(null=True, verbose_name='Заголовок "Документальный отчет"'),
        ),
        migrations.AddField(
            model_name='studenttitles',
            name='document_report_ru',
            field=models.URLField(null=True, verbose_name='Заголовок "Документальный отчет"'),
        ),
        migrations.AddField(
            model_name='studenttitles',
            name='tasks',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок "Задачи"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenttitles',
            name='tasks_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Задачи"'),
        ),
        migrations.AddField(
            model_name='studenttitles',
            name='tasks_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Задачи"'),
        ),
        migrations.AddField(
            model_name='studenttitles',
            name='tasks_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Задачи"'),
        ),
        migrations.AddField(
            model_name='studenttitles',
            name='text_report',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок "Текстовый отчет"'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studenttitles',
            name='text_report_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Текстовый отчет"'),
        ),
        migrations.AddField(
            model_name='studenttitles',
            name='text_report_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Текстовый отчет"'),
        ),
        migrations.AddField(
            model_name='studenttitles',
            name='text_report_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок "Текстовый отчет"'),
        ),
    ]
