# Generated by Django 5.2 on 2025-07-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_delete_titlesreport_studenttitles_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttitles',
            name='deadline',
            field=models.CharField(default='Дедлайн', max_length=255, verbose_name='Заголовок "Дедлайн"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='deadline_en',
            field=models.CharField(default='Дедлайн', max_length=255, null=True, verbose_name='Заголовок "Дедлайн"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='deadline_ky',
            field=models.CharField(default='Дедлайн', max_length=255, null=True, verbose_name='Заголовок "Дедлайн"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='deadline_ru',
            field=models.CharField(default='Дедлайн', max_length=255, null=True, verbose_name='Заголовок "Дедлайн"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='document_report',
            field=models.URLField(default='Документальный отчет', verbose_name='Заголовок "Документальный отчет"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='document_report_en',
            field=models.URLField(default='Документальный отчет', null=True, verbose_name='Заголовок "Документальный отчет"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='document_report_ky',
            field=models.URLField(default='Документальный отчет', null=True, verbose_name='Заголовок "Документальный отчет"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='document_report_ru',
            field=models.URLField(default='Документальный отчет', null=True, verbose_name='Заголовок "Документальный отчет"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='tasks',
            field=models.CharField(default='Задачи', max_length=255, verbose_name='Заголовок "Задачи"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='tasks_en',
            field=models.CharField(default='Задачи', max_length=255, null=True, verbose_name='Заголовок "Задачи"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='tasks_ky',
            field=models.CharField(default='Задачи', max_length=255, null=True, verbose_name='Заголовок "Задачи"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='tasks_ru',
            field=models.CharField(default='Задачи', max_length=255, null=True, verbose_name='Заголовок "Задачи"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='text_report',
            field=models.CharField(default='Текстовый отчет', max_length=255, verbose_name='Заголовок "Текстовый отчет"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='text_report_en',
            field=models.CharField(default='Текстовый отчет', max_length=255, null=True, verbose_name='Заголовок "Текстовый отчет"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='text_report_ky',
            field=models.CharField(default='Текстовый отчет', max_length=255, null=True, verbose_name='Заголовок "Текстовый отчет"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='text_report_ru',
            field=models.CharField(default='Текстовый отчет', max_length=255, null=True, verbose_name='Заголовок "Текстовый отчет"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='title_document',
            field=models.CharField(default='Документ', max_length=255, verbose_name='Заголовок "Документ"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='title_document_en',
            field=models.CharField(default='Документ', max_length=255, null=True, verbose_name='Заголовок "Документ"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='title_document_ky',
            field=models.CharField(default='Документ', max_length=255, null=True, verbose_name='Заголовок "Документ"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='title_document_ru',
            field=models.CharField(default='Документ', max_length=255, null=True, verbose_name='Заголовок "Документ"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='title_documents',
            field=models.CharField(default='Документы', max_length=255, verbose_name='Заголовок "Документы"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='title_documents_en',
            field=models.CharField(default='Документы', max_length=255, null=True, verbose_name='Заголовок "Документы"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='title_documents_ky',
            field=models.CharField(default='Документы', max_length=255, null=True, verbose_name='Заголовок "Документы"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='title_documents_ru',
            field=models.CharField(default='Документы', max_length=255, null=True, verbose_name='Заголовок "Документы"'),
        ),
    ]
