# Generated by Django 5.2 on 2025-07-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_sendingreport_practice_alter_sendingreport_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiaryEntry',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
