# Generated by Django 5.2 on 2025-07-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_delete_diaryentry_delete_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingreport',
            name='file_report',
            field=models.FileField(upload_to='media/files/', verbose_name='файл отчета'),
        ),
    ]
