# Generated by Django 5.2 on 2025-07-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_alter_sendingreport_file_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcharacteristic',
            name='title_document',
        ),
        migrations.RemoveField(
            model_name='studentcharacteristic',
            name='title_document_en',
        ),
        migrations.RemoveField(
            model_name='studentcharacteristic',
            name='title_document_ky',
        ),
        migrations.RemoveField(
            model_name='studentcharacteristic',
            name='title_document_ru',
        ),
        migrations.RemoveField(
            model_name='studentcharacteristic',
            name='title_filename',
        ),
        migrations.AddField(
            model_name='studentcharacteristic',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characteristics', to='students.sendingreport'),
        ),
    ]
