# Generated by Django 5.2 on 2025-07-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_alter_sendingreport_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentCharacteristic',
        ),
    ]
