# Generated by Django 5.2 on 2025-07-24 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_delete_studentcharacteristic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/files/extra/', verbose_name='Доп. файл')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_files', to='students.sendingreport')),
            ],
        ),
    ]
