# Generated by Django 5.2 on 2025-07-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_additionalfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfile',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_files', to='students.sendingreport'),
        ),
    ]
