# Generated by Django 5.2 on 2025-07-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_reportfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalFile',
        ),
    ]
