# Generated by Django 5.2 on 2025-07-25 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_delete_additionalfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportFile',
        ),
    ]
