# Generated by Django 5.2 on 2025-07-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingreport',
            name='file_report_2',
            field=models.FileField(default=1, upload_to='media/files/', verbose_name='файл отчета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sendingreport',
            name='file_report_3',
            field=models.FileField(default=1, upload_to='media/files/', verbose_name='файл отчета'),
            preserve_default=False,
        ),
    ]
