# Generated by Django 5.2 on 2025-07-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_sendingreport_file_report_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingreport',
            name='file_report',
            field=models.FileField(blank=True, null=True, upload_to='media/files/', verbose_name='файл отчета'),
        ),
        migrations.AlterField(
            model_name='sendingreport',
            name='file_report_2',
            field=models.FileField(blank=True, null=True, upload_to='media/files/', verbose_name='файл отчета'),
        ),
        migrations.AlterField(
            model_name='sendingreport',
            name='file_report_3',
            field=models.FileField(blank=True, null=True, upload_to='media/files/', verbose_name='файл отчета'),
        ),
    ]
