# Generated by Django 5.2 on 2025-07-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0034_alter_sendingreport_file_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingreport',
            name='file_report_4',
            field=models.FileField(blank=True, null=True, upload_to='media/files/', verbose_name='файл отчета'),
        ),
    ]
