# Generated by Django 4.2.5 on 2025-07-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0035_sendingreport_file_report_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttitles',
            name='document_report',
            field=models.CharField(default='Документальный отчет', max_length=255, verbose_name='Заголовок "Документальный отчет"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='document_report_en',
            field=models.CharField(default='Документальный отчет', max_length=255, null=True, verbose_name='Заголовок "Документальный отчет"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='document_report_ky',
            field=models.CharField(default='Документальный отчет', max_length=255, null=True, verbose_name='Заголовок "Документальный отчет"'),
        ),
        migrations.AlterField(
            model_name='studenttitles',
            name='document_report_ru',
            field=models.CharField(default='Документальный отчет', max_length=255, null=True, verbose_name='Заголовок "Документальный отчет"'),
        ),
    ]
