# Generated by Django 5.2 on 2025-07-09 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('role', models.CharField(blank=True, max_length=20, null=True, verbose_name='Роль пользователя')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Время входа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Журнал входа',
                'verbose_name_plural': 'Журналы входа',
                'ordering': ['-login_time'],
            },
        ),
    ]
