# Generated by Django 5.2 on 2025-07-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_faculty_user_institution_user_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_fkj',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Логин'),
        ),
    ]
