# Generated by Django 5.2 on 2025-07-10 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0004_faculty_faculty_en_faculty_faculty_ky_and_more'),
        ('users', '0002_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SuperAdmin.faculty', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Полное имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('fkj', 'ФКЖ'), ('admin', 'Суперадмин')], default='student', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
