# Generated by Django 5.2 on 2025-07-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_faculty_user_full_name_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
