# Generated by Django 5.2 on 2025-07-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Полное имя'),
            preserve_default=False,
        ),
    ]
