# Generated by Django 5.2 on 2025-07-13 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0009_alter_institution_options'),
        ('users', '0008_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SuperAdmin.faculty'),
        ),
    ]
