# Generated by Django 5.2 on 2025-07-13 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0009_alter_institution_options'),
        ('users', '0010_alter_user_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SuperAdmin.faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('fkj', 'ФКЖ'), ('admin', 'Суперадмин')], default='student', max_length=20, verbose_name='Роль'),
        ),
    ]
