# Generated by Django 5.2 on 2025-07-16 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0011_alter_titlesadmin_address_and_more'),
        ('users', '0013_alter_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SuperAdmin.institution', verbose_name='Учреждение'),
        ),
        migrations.AddField(
            model_name='user',
            name='special',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SuperAdmin.speciality', verbose_name='Специальность'),
        ),
    ]
