# Generated by Django 5.2 on 2025-07-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_institution_user_special'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='special',
            new_name='speciality',
        ),
    ]
