# Generated by Django 5.2 on 2025-07-09 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.PositiveSmallIntegerField(choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс')], verbose_name='Курсы')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(help_text='Номер дня в курсе', verbose_name='День')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='SuperAdmin.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Загрузить логотип учреждения', null=True, upload_to='logos/', verbose_name='Логотип учреждения')),
                ('name', models.CharField(help_text='Введите название учреждения/организации', max_length=255, verbose_name='Название')),
                ('type', models.CharField(help_text='Введите тип учреждения/оригнизации', max_length=255, verbose_name='Тип')),
                ('contact', models.CharField(help_text='Введите номер телефона учреждения/оригнизации', max_length=20, verbose_name='Контакт')),
                ('address', models.TextField(help_text='Введите адрес учреждения/оригнизации', verbose_name='Адрес')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Создание учреждения',
                'verbose_name_plural': 'Создание учреждении',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='SuperAdmin.institution', verbose_name='Учиреждение'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Введите задание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядковый номер задачи')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='SuperAdmin.day', verbose_name='День')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'задания',
                'ordering': ['order'],
            },
        ),
    ]
