# Generated by Django 5.2 on 2025-07-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0002_faculty_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='task',
            name='day',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
