# Generated by Django 5.2 on 2025-07-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0003_remove_day_courses_remove_task_day_delete_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='speciality_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='speciality_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='speciality',
            name='speciality_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Специальность'),
        ),
    ]
