# Generated by Django 5.2 on 2025-07-13 06:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0004_faculty_faculty_en_faculty_faculty_ky_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок документа')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок документа')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок документа')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок документа')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержание документа')),
                ('content_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание документа')),
                ('content_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание документа')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание документа')),
            ],
            options={
                'verbose_name': 'Документ студента',
                'verbose_name_plural': 'Документы студентов',
            },
        ),
    ]
