# Generated by Django 5.2 on 2025-07-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0005_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='user',
        ),
    ]
