# Generated by Django 5.2 on 2025-07-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0006_remove_institution_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='address_en',
            field=models.TextField(help_text='Введите адрес учреждения/оригнизации', null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='institution',
            name='address_ky',
            field=models.TextField(help_text='Введите адрес учреждения/оригнизации', null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='institution',
            name='address_ru',
            field=models.TextField(help_text='Введите адрес учреждения/оригнизации', null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='institution',
            name='name_en',
            field=models.CharField(help_text='Введите название учреждения/организации', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='institution',
            name='name_ky',
            field=models.CharField(help_text='Введите название учреждения/организации', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='institution',
            name='name_ru',
            field=models.CharField(help_text='Введите название учреждения/организации', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='institution',
            name='type_en',
            field=models.CharField(help_text='Введите тип учреждения/оригнизации', max_length=255, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='institution',
            name='type_ky',
            field=models.CharField(help_text='Введите тип учреждения/оригнизации', max_length=255, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='institution',
            name='type_ru',
            field=models.CharField(help_text='Введите тип учреждения/оригнизации', max_length=255, null=True, verbose_name='Тип'),
        ),
    ]
