# Generated by Django 5.2 on 2025-07-13 12:31

import apps.SuperAdmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0007_institution_address_en_institution_address_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='contact',
            field=models.CharField(help_text='Введите номер телефона учреждения/оригнизации', max_length=20, validators=[apps.SuperAdmin.models.Institution.validate_phone_number], verbose_name='Контакт'),
        ),
    ]
