# Generated by Django 5.2 on 2025-07-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0008_alter_institution_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Создание учреждения', 'verbose_name_plural': 'Создание учреждений'},
        ),
    ]
