# Generated by Django 5.2 on 2025-07-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0010_titlesadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlesadmin',
            name='address',
            field=models.CharField(default='Адрес', max_length=300, verbose_name='Заголовок "Адрес"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='address_en',
            field=models.CharField(default='Адрес', max_length=300, null=True, verbose_name='Заголовок "Адрес"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='address_ky',
            field=models.CharField(default='Адрес', max_length=300, null=True, verbose_name='Заголовок "Адрес"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='address_ru',
            field=models.CharField(default='Адрес', max_length=300, null=True, verbose_name='Заголовок "Адрес"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='contacts',
            field=models.CharField(default='Контакты', max_length=300, verbose_name='Заголовок "Контакты"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='contacts_en',
            field=models.CharField(default='Контакты', max_length=300, null=True, verbose_name='Заголовок "Контакты"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='contacts_ky',
            field=models.CharField(default='Контакты', max_length=300, null=True, verbose_name='Заголовок "Контакты"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='contacts_ru',
            field=models.CharField(default='Контакты', max_length=300, null=True, verbose_name='Заголовок "Контакты"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='course',
            field=models.CharField(default='Курс', max_length=300, verbose_name='Заголовок "Курс"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='course_en',
            field=models.CharField(default='Курс', max_length=300, null=True, verbose_name='Заголовок "Курс"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='course_ky',
            field=models.CharField(default='Курс', max_length=300, null=True, verbose_name='Заголовок "Курс"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='course_ru',
            field=models.CharField(default='Курс', max_length=300, null=True, verbose_name='Заголовок "Курс"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='faculty',
            field=models.CharField(default='Факультет', max_length=300, verbose_name='Заголовок "Факультет"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='faculty_en',
            field=models.CharField(default='Факультет', max_length=300, null=True, verbose_name='Заголовок "Факультет"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='faculty_ky',
            field=models.CharField(default='Факультет', max_length=300, null=True, verbose_name='Заголовок "Факультет"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='faculty_ru',
            field=models.CharField(default='Факультет', max_length=300, null=True, verbose_name='Заголовок "Факультет"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='full_name',
            field=models.CharField(default='ФИО', max_length=300, verbose_name='Заголовок "ФИО"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='full_name_en',
            field=models.CharField(default='ФИО', max_length=300, null=True, verbose_name='Заголовок "ФИО"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='full_name_fkj',
            field=models.CharField(default='Имя фамилия ФКЖ', max_length=300, verbose_name='Заголовок "Имя фамилия ФКЖ"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='full_name_fkj_en',
            field=models.CharField(default='Имя фамилия ФКЖ', max_length=300, null=True, verbose_name='Заголовок "Имя фамилия ФКЖ"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='full_name_fkj_ky',
            field=models.CharField(default='Имя фамилия ФКЖ', max_length=300, null=True, verbose_name='Заголовок "Имя фамилия ФКЖ"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='full_name_fkj_ru',
            field=models.CharField(default='Имя фамилия ФКЖ', max_length=300, null=True, verbose_name='Заголовок "Имя фамилия ФКЖ"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='full_name_ky',
            field=models.CharField(default='ФИО', max_length=300, null=True, verbose_name='Заголовок "ФИО"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='full_name_ru',
            field=models.CharField(default='ФИО', max_length=300, null=True, verbose_name='Заголовок "ФИО"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='institution',
            field=models.CharField(default='Учреждение', max_length=300, verbose_name='Заголовок "Учреждение"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='institution_en',
            field=models.CharField(default='Учреждение', max_length=300, null=True, verbose_name='Заголовок "Учреждение"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='institution_ky',
            field=models.CharField(default='Учреждение', max_length=300, null=True, verbose_name='Заголовок "Учреждение"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='institution_organization',
            field=models.CharField(default='Учреждение/Организация', max_length=300, verbose_name='Заголовок "Учреждение/Организация"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='institution_organization_en',
            field=models.CharField(default='Учреждение/Организация', max_length=300, null=True, verbose_name='Заголовок "Учреждение/Организация"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='institution_organization_ky',
            field=models.CharField(default='Учреждение/Организация', max_length=300, null=True, verbose_name='Заголовок "Учреждение/Организация"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='institution_organization_ru',
            field=models.CharField(default='Учреждение/Организация', max_length=300, null=True, verbose_name='Заголовок "Учреждение/Организация"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='institution_ru',
            field=models.CharField(default='Учреждение', max_length=300, null=True, verbose_name='Заголовок "Учреждение"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='login',
            field=models.CharField(default='Логин', max_length=300, verbose_name='Заголовок "Логин"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='login_en',
            field=models.CharField(default='Логин', max_length=300, null=True, verbose_name='Заголовок "Логин"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='login_ky',
            field=models.CharField(default='Логин', max_length=300, null=True, verbose_name='Заголовок "Логин"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='login_ru',
            field=models.CharField(default='Логин', max_length=300, null=True, verbose_name='Заголовок "Логин"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='metodist',
            field=models.CharField(default='Методист', max_length=300, verbose_name='Заголовок "Методист"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='metodist_en',
            field=models.CharField(default='Методист', max_length=300, null=True, verbose_name='Заголовок "Методист"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='metodist_ky',
            field=models.CharField(default='Методист', max_length=300, null=True, verbose_name='Заголовок "Методист"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='metodist_ru',
            field=models.CharField(default='Методист', max_length=300, null=True, verbose_name='Заголовок "Методист"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='name',
            field=models.CharField(default='Название', max_length=300, verbose_name='Заголовок "Название"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='name_en',
            field=models.CharField(default='Название', max_length=300, null=True, verbose_name='Заголовок "Название"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='name_ky',
            field=models.CharField(default='Название', max_length=300, null=True, verbose_name='Заголовок "Название"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='name_ru',
            field=models.CharField(default='Название', max_length=300, null=True, verbose_name='Заголовок "Название"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='password',
            field=models.CharField(default='Пароль', max_length=300, verbose_name='Заголовок "Пароль"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='password_en',
            field=models.CharField(default='Пароль', max_length=300, null=True, verbose_name='Заголовок "Пароль"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='password_ky',
            field=models.CharField(default='Пароль', max_length=300, null=True, verbose_name='Заголовок "Пароль"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='password_ru',
            field=models.CharField(default='Пароль', max_length=300, null=True, verbose_name='Заголовок "Пароль"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='period',
            field=models.CharField(default='Период', max_length=300, verbose_name='Заголовок "Период"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='period_en',
            field=models.CharField(default='Период', max_length=300, null=True, verbose_name='Заголовок "Период"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='period_ky',
            field=models.CharField(default='Период', max_length=300, null=True, verbose_name='Заголовок "Период"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='period_ru',
            field=models.CharField(default='Период', max_length=300, null=True, verbose_name='Заголовок "Период"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='phone_number',
            field=models.CharField(default='Телефон', max_length=300, verbose_name='Заголовок "Телефон"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='phone_number_en',
            field=models.CharField(default='Телефон', max_length=300, null=True, verbose_name='Заголовок "Телефон"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='phone_number_ky',
            field=models.CharField(default='Телефон', max_length=300, null=True, verbose_name='Заголовок "Телефон"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='phone_number_ru',
            field=models.CharField(default='Телефон', max_length=300, null=True, verbose_name='Заголовок "Телефон"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='students',
            field=models.CharField(default='Студенты', max_length=300, verbose_name='Заголовок "Студенты"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='students_en',
            field=models.CharField(default='Студенты', max_length=300, null=True, verbose_name='Заголовок "Студенты"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='students_ky',
            field=models.CharField(default='Студенты', max_length=300, null=True, verbose_name='Заголовок "Студенты"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='students_ru',
            field=models.CharField(default='Студенты', max_length=300, null=True, verbose_name='Заголовок "Студенты"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='type',
            field=models.CharField(default='Тип', max_length=300, verbose_name='Заголовок "Тип"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='type_en',
            field=models.CharField(default='Тип', max_length=300, null=True, verbose_name='Заголовок "Тип"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='type_institution',
            field=models.CharField(default='Тип учреждения', max_length=300, verbose_name='Заголовок "Тип учреждения"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='type_institution_en',
            field=models.CharField(default='Тип учреждения', max_length=300, null=True, verbose_name='Заголовок "Тип учреждения"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='type_institution_ky',
            field=models.CharField(default='Тип учреждения', max_length=300, null=True, verbose_name='Заголовок "Тип учреждения"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='type_institution_ru',
            field=models.CharField(default='Тип учреждения', max_length=300, null=True, verbose_name='Заголовок "Тип учреждения"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='type_ky',
            field=models.CharField(default='Тип', max_length=300, null=True, verbose_name='Заголовок "Тип"'),
        ),
        migrations.AlterField(
            model_name='titlesadmin',
            name='type_ru',
            field=models.CharField(default='Тип', max_length=300, null=True, verbose_name='Заголовок "Тип"'),
        ),
    ]
