# Generated by Django 5.2 on 2025-07-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0011_alter_titlesadmin_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255, verbose_name='Язык обучения')),
                ('language_ru', models.CharField(max_length=255, null=True, verbose_name='Язык обучения')),
                ('language_ky', models.CharField(max_length=255, null=True, verbose_name='Язык обучения')),
                ('language_en', models.CharField(max_length=255, null=True, verbose_name='Язык обучения')),
            ],
            options={
                'verbose_name': 'Язык обучения',
                'verbose_name_plural': 'Языки обучения',
            },
        ),
    ]
