# Generated by Django 5.2 on 2025-07-23 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0012_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='fkj',
            field=models.ManyToManyField(limit_choices_to={'role': 'fkj'}, related_name='fkj', to=settings.AUTH_USER_MODEL, verbose_name='ФКЖ'),
        ),
    ]
