# Generated by Django 5.2 on 2025-07-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0013_institution_fkj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(help_text='Введите тип учреждения/организации', max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type_en',
            field=models.CharField(help_text='Введите тип учреждения/организации', max_length=255, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type_ky',
            field=models.CharField(help_text='Введите тип учреждения/организации', max_length=255, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type_ru',
            field=models.CharField(help_text='Введите тип учреждения/организации', max_length=255, null=True, verbose_name='Тип'),
        ),
    ]
