# Generated by Django 5.2 on 2025-07-27 13:17

import apps.SuperAdmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0014_alter_institution_type_alter_institution_type_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.TextField(help_text='Введите адрес учреждения/организации', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address_en',
            field=models.TextField(help_text='Введите адрес учреждения/организации', null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address_ky',
            field=models.TextField(help_text='Введите адрес учреждения/организации', null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address_ru',
            field=models.TextField(help_text='Введите адрес учреждения/организации', null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='contact',
            field=models.CharField(help_text='Введите номер телефона учреждения/организации', max_length=20, validators=[apps.SuperAdmin.models.Institution.validate_phone_number], verbose_name='Контакт'),
        ),
    ]
