# Generated by Django 5.2 on 2025-07-09 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FKJUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True, verbose_name='Имя пользователя ФКЖ')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fkj', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь ФКЖ',
                'verbose_name_plural': 'Пользователи ФКЖ',
            },
        ),
    ]
