# Generated by Django 5.2 on 2025-07-09 14:01

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0001_initial'),
        ('SuperAdmin', '0002_faculty_speciality'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_type', models.CharField(choices=[('Introductory', 'Ознакомительная'), ('Professionally_Oriented', 'Профессионально-профильная'), ('Pre_Qualification', 'Предквалификационная')], max_length=30)),
                ('start_date', models.DateField(verbose_name='Дата начала практики')),
                ('end_date', models.DateField(verbose_name='Дата окончания практики')),
                ('work_days', multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Пн'), ('Tue', 'Вт'), ('Wed', 'Ср'), ('Thu', 'Чт'), ('Fri', 'Пт'), ('Sat', 'Сб'), ('Sun', 'Вс')], max_length=27)),
                ('start_time', models.TimeField(verbose_name='Время начала практики')),
                ('end_time', models.TimeField(verbose_name='Время окончания практики')),
                ('reception', models.CharField(choices=[('Winter', 'Зимний'), ('Autumn', 'Осенний')], max_length=20)),
                ('semester', models.CharField(choices=[('Autumn', 'Осенний'), ('Spring', 'Весенний')], max_length=20)),
                ('education_form', models.CharField(choices=[('Full_Time', 'Очная'), ('Part_Time', 'Заочная'), ('Blended', 'Очно-заочная')], max_length=20)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practices', to='SuperAdmin.faculty', verbose_name='Факультет')),
                ('speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialty_practices', to='SuperAdmin.speciality', verbose_name='Специальность')),
                ('students', models.ManyToManyField(blank=True, related_name='practices', to='students.studentprofile', verbose_name='Студенты')),
            ],
            options={
                'verbose_name': 'Создание практики',
                'verbose_name_plural': 'Создание практик',
            },
        ),
    ]
