# Generated by Django 5.2 on 2025-07-09 14:08

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0002_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='fkjuser',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Имя пользователя ФКЖ'),
        ),
        migrations.AddField(
            model_name='fkjuser',
            name='full_name_ky',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Имя пользователя ФКЖ'),
        ),
        migrations.AddField(
            model_name='fkjuser',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Имя пользователя ФКЖ'),
        ),
        migrations.AddField(
            model_name='practice',
            name='education_form_en',
            field=models.CharField(choices=[('Full_Time', 'Очная'), ('Part_Time', 'Заочная'), ('Blended', 'Очно-заочная')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='education_form_ky',
            field=models.CharField(choices=[('Full_Time', 'Очная'), ('Part_Time', 'Заочная'), ('Blended', 'Очно-заочная')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='education_form_ru',
            field=models.CharField(choices=[('Full_Time', 'Очная'), ('Part_Time', 'Заочная'), ('Blended', 'Очно-заочная')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='end_date_en',
            field=models.DateField(null=True, verbose_name='Дата окончания практики'),
        ),
        migrations.AddField(
            model_name='practice',
            name='end_date_ky',
            field=models.DateField(null=True, verbose_name='Дата окончания практики'),
        ),
        migrations.AddField(
            model_name='practice',
            name='end_date_ru',
            field=models.DateField(null=True, verbose_name='Дата окончания практики'),
        ),
        migrations.AddField(
            model_name='practice',
            name='end_time_en',
            field=models.TimeField(null=True, verbose_name='Время окончания практики'),
        ),
        migrations.AddField(
            model_name='practice',
            name='end_time_ky',
            field=models.TimeField(null=True, verbose_name='Время окончания практики'),
        ),
        migrations.AddField(
            model_name='practice',
            name='end_time_ru',
            field=models.TimeField(null=True, verbose_name='Время окончания практики'),
        ),
        migrations.AddField(
            model_name='practice',
            name='practice_type_en',
            field=models.CharField(choices=[('Introductory', 'Ознакомительная'), ('Professionally_Oriented', 'Профессионально-профильная'), ('Pre_Qualification', 'Предквалификационная')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='practice_type_ky',
            field=models.CharField(choices=[('Introductory', 'Ознакомительная'), ('Professionally_Oriented', 'Профессионально-профильная'), ('Pre_Qualification', 'Предквалификационная')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='practice_type_ru',
            field=models.CharField(choices=[('Introductory', 'Ознакомительная'), ('Professionally_Oriented', 'Профессионально-профильная'), ('Pre_Qualification', 'Предквалификационная')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='reception_en',
            field=models.CharField(choices=[('Winter', 'Зимний'), ('Autumn', 'Осенний')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='reception_ky',
            field=models.CharField(choices=[('Winter', 'Зимний'), ('Autumn', 'Осенний')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='reception_ru',
            field=models.CharField(choices=[('Winter', 'Зимний'), ('Autumn', 'Осенний')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='semester_en',
            field=models.CharField(choices=[('Autumn', 'Осенний'), ('Spring', 'Весенний')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='semester_ky',
            field=models.CharField(choices=[('Autumn', 'Осенний'), ('Spring', 'Весенний')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='semester_ru',
            field=models.CharField(choices=[('Autumn', 'Осенний'), ('Spring', 'Весенний')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='start_date_en',
            field=models.DateField(null=True, verbose_name='Дата начала практики'),
        ),
        migrations.AddField(
            model_name='practice',
            name='start_date_ky',
            field=models.DateField(null=True, verbose_name='Дата начала практики'),
        ),
        migrations.AddField(
            model_name='practice',
            name='start_date_ru',
            field=models.DateField(null=True, verbose_name='Дата начала практики'),
        ),
        migrations.AddField(
            model_name='practice',
            name='start_time_en',
            field=models.TimeField(null=True, verbose_name='Время начала практики'),
        ),
        migrations.AddField(
            model_name='practice',
            name='start_time_ky',
            field=models.TimeField(null=True, verbose_name='Время начала практики'),
        ),
        migrations.AddField(
            model_name='practice',
            name='start_time_ru',
            field=models.TimeField(null=True, verbose_name='Время начала практики'),
        ),
        migrations.AddField(
            model_name='practice',
            name='work_days_en',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Пн'), ('Tue', 'Вт'), ('Wed', 'Ср'), ('Thu', 'Чт'), ('Fri', 'Пт'), ('Sat', 'Сб'), ('Sun', 'Вс')], max_length=27, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='work_days_ky',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Пн'), ('Tue', 'Вт'), ('Wed', 'Ср'), ('Thu', 'Чт'), ('Fri', 'Пт'), ('Sat', 'Сб'), ('Sun', 'Вс')], max_length=27, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='work_days_ru',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Пн'), ('Tue', 'Вт'), ('Wed', 'Ср'), ('Thu', 'Чт'), ('Fri', 'Пт'), ('Sat', 'Сб'), ('Sun', 'Вс')], max_length=27, null=True),
        ),
    ]
