# Generated by Django 5.2 on 2025-07-09 14:13

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0003_fkjuser_full_name_en_fkjuser_full_name_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='education_form',
            field=models.CharField(choices=[('Full_Time', 'Очная'), ('Part_Time', 'Заочная'), ('Blended', 'Очно-заочная')], max_length=20, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='education_form_en',
            field=models.CharField(choices=[('Full_Time', 'Очная'), ('Part_Time', 'Заочная'), ('Blended', 'Очно-заочная')], max_length=20, null=True, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='education_form_ky',
            field=models.CharField(choices=[('Full_Time', 'Очная'), ('Part_Time', 'Заочная'), ('Blended', 'Очно-заочная')], max_length=20, null=True, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='education_form_ru',
            field=models.CharField(choices=[('Full_Time', 'Очная'), ('Part_Time', 'Заочная'), ('Blended', 'Очно-заочная')], max_length=20, null=True, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='practice_type',
            field=models.CharField(choices=[('Introductory', 'Ознакомительная'), ('Professionally_Oriented', 'Профессионально-профильная'), ('Pre_Qualification', 'Предквалификационная')], max_length=30, verbose_name='Тип практики'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='practice_type_en',
            field=models.CharField(choices=[('Introductory', 'Ознакомительная'), ('Professionally_Oriented', 'Профессионально-профильная'), ('Pre_Qualification', 'Предквалификационная')], max_length=30, null=True, verbose_name='Тип практики'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='practice_type_ky',
            field=models.CharField(choices=[('Introductory', 'Ознакомительная'), ('Professionally_Oriented', 'Профессионально-профильная'), ('Pre_Qualification', 'Предквалификационная')], max_length=30, null=True, verbose_name='Тип практики'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='practice_type_ru',
            field=models.CharField(choices=[('Introductory', 'Ознакомительная'), ('Professionally_Oriented', 'Профессионально-профильная'), ('Pre_Qualification', 'Предквалификационная')], max_length=30, null=True, verbose_name='Тип практики'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='reception',
            field=models.CharField(choices=[('Winter', 'Зимний'), ('Autumn', 'Осенний')], max_length=20, verbose_name='Прием'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='reception_en',
            field=models.CharField(choices=[('Winter', 'Зимний'), ('Autumn', 'Осенний')], max_length=20, null=True, verbose_name='Прием'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='reception_ky',
            field=models.CharField(choices=[('Winter', 'Зимний'), ('Autumn', 'Осенний')], max_length=20, null=True, verbose_name='Прием'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='reception_ru',
            field=models.CharField(choices=[('Winter', 'Зимний'), ('Autumn', 'Осенний')], max_length=20, null=True, verbose_name='Прием'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='semester',
            field=models.CharField(choices=[('Autumn', 'Осенний'), ('Spring', 'Весенний')], max_length=20, verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='semester_en',
            field=models.CharField(choices=[('Autumn', 'Осенний'), ('Spring', 'Весенний')], max_length=20, null=True, verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='semester_ky',
            field=models.CharField(choices=[('Autumn', 'Осенний'), ('Spring', 'Весенний')], max_length=20, null=True, verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='semester_ru',
            field=models.CharField(choices=[('Autumn', 'Осенний'), ('Spring', 'Весенний')], max_length=20, null=True, verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='work_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Пн'), ('Tue', 'Вт'), ('Wed', 'Ср'), ('Thu', 'Чт'), ('Fri', 'Пт'), ('Sat', 'Сб'), ('Sun', 'Вс')], max_length=27, verbose_name='Дни практики'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='work_days_en',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Пн'), ('Tue', 'Вт'), ('Wed', 'Ср'), ('Thu', 'Чт'), ('Fri', 'Пт'), ('Sat', 'Сб'), ('Sun', 'Вс')], max_length=27, null=True, verbose_name='Дни практики'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='work_days_ky',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Пн'), ('Tue', 'Вт'), ('Wed', 'Ср'), ('Thu', 'Чт'), ('Fri', 'Пт'), ('Sat', 'Сб'), ('Sun', 'Вс')], max_length=27, null=True, verbose_name='Дни практики'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='work_days_ru',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Пн'), ('Tue', 'Вт'), ('Wed', 'Ср'), ('Thu', 'Чт'), ('Fri', 'Пт'), ('Sat', 'Сб'), ('Sun', 'Вс')], max_length=27, null=True, verbose_name='Дни практики'),
        ),
    ]
