# Generated by Django 5.2 on 2025-07-09 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0004_alter_practice_education_form_and_more'),
        ('SuperAdmin', '0002_faculty_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='faculty_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practices', to='SuperAdmin.faculty', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='practice',
            name='faculty_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practices', to='SuperAdmin.faculty', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='practice',
            name='faculty_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practices', to='SuperAdmin.faculty', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='practice',
            name='speciality_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialty_practices', to='SuperAdmin.speciality', verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='practice',
            name='speciality_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialty_practices', to='SuperAdmin.speciality', verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='practice',
            name='speciality_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialty_practices', to='SuperAdmin.speciality', verbose_name='Специальность'),
        ),
    ]
