# Generated by Django 5.2 on 2025-07-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0005_practice_faculty_en_practice_faculty_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='reception',
            field=models.CharField(choices=[('Winter', 'Зимний'), ('Autumn', 'Осенний')], max_length=20, verbose_name='Приём'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='reception_en',
            field=models.CharField(choices=[('Winter', 'Зимний'), ('Autumn', 'Осенний')], max_length=20, null=True, verbose_name='Приём'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='reception_ky',
            field=models.CharField(choices=[('Winter', 'Зимний'), ('Autumn', 'Осенний')], max_length=20, null=True, verbose_name='Приём'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='reception_ru',
            field=models.CharField(choices=[('Winter', 'Зимний'), ('Autumn', 'Осенний')], max_length=20, null=True, verbose_name='Приём'),
        ),
    ]
