# Generated by Django 5.2 on 2025-07-10 06:19

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0006_alter_practice_reception_alter_practice_reception_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='work_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Понедельник'), ('Tue', 'Вторник'), ('Wed', 'Среда'), ('Thu', 'Четверг'), ('Fri', 'Пятница'), ('Sat', 'Суббота'), ('Sun', 'Воскресенье')], max_length=27, verbose_name='Дни практики'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='work_days_en',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Понедельник'), ('Tue', 'Вторник'), ('Wed', 'Среда'), ('Thu', 'Четверг'), ('Fri', 'Пятница'), ('Sat', 'Суббота'), ('Sun', 'Воскресенье')], max_length=27, null=True, verbose_name='Дни практики'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='work_days_ky',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Понедельник'), ('Tue', 'Вторник'), ('Wed', 'Среда'), ('Thu', 'Четверг'), ('Fri', 'Пятница'), ('Sat', 'Суббота'), ('Sun', 'Воскресенье')], max_length=27, null=True, verbose_name='Дни практики'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='work_days_ru',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Понедельник'), ('Tue', 'Вторник'), ('Wed', 'Среда'), ('Thu', 'Четверг'), ('Fri', 'Пятница'), ('Sat', 'Суббота'), ('Sun', 'Воскресенье')], max_length=27, null=True, verbose_name='Дни практики'),
        ),
    ]
