# Generated by Django 5.2 on 2025-07-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0007_alter_practice_work_days_alter_practice_work_days_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FKJUser',
        ),
    ]
