# Generated by Django 5.2 on 2025-07-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0008_delete_fkjuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='numder',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер практики'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practice',
            name='numder_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер практики'),
        ),
        migrations.AddField(
            model_name='practice',
            name='numder_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер практики'),
        ),
        migrations.AddField(
            model_name='practice',
            name='numder_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер практики'),
        ),
    ]
