# Generated by Django 5.2 on 2025-07-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0009_practice_numder_practice_numder_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс')], null=True, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='practice',
            name='course_en',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс')], null=True, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='practice',
            name='course_ky',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс')], null=True, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='practice',
            name='course_ru',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс')], null=True, verbose_name='Курс'),
        ),
    ]
