# Generated by Django 5.2 on 2025-07-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0010_practice_course_practice_course_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='course_en',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='course_ky',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='course_ru',
        ),
    ]
