# Generated by Django 5.2 on 2025-07-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0011_remove_practice_course_en_remove_practice_course_ky_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practice',
            old_name='numder',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='practice',
            old_name='numder_en',
            new_name='number_en',
        ),
        migrations.RenameField(
            model_name='practice',
            old_name='numder_ky',
            new_name='number_ky',
        ),
        migrations.RenameField(
            model_name='practice',
            old_name='numder_ru',
            new_name='number_ru',
        ),
    ]
