# Generated by Django 5.2 on 2025-07-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0012_rename_numder_practice_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitlesFkj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=255, verbose_name='Заголовок "Период:"')),
                ('period_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Период:"')),
                ('period_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Период:"')),
                ('period_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Период:"')),
                ('working_days', models.CharField(max_length=255, verbose_name='Заголовок "Рабочие дни:"')),
                ('working_days_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Рабочие дни:"')),
                ('working_days_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Рабочие дни:"')),
                ('working_days_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Рабочие дни:"')),
                ('opening_hours', models.CharField(max_length=255, verbose_name='Заголовок "Часы работы:"')),
                ('opening_hours_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Часы работы:"')),
                ('opening_hours_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Часы работы:"')),
                ('opening_hours_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Часы работы:"')),
                ('type_of_practice', models.CharField(max_length=255, verbose_name='Заголовок "Тип практики:"')),
                ('type_of_practice_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Тип практики:"')),
                ('type_of_practice_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Тип практики:"')),
                ('type_of_practice_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Тип практики:"')),
                ('add_students', models.CharField(max_length=255, verbose_name='Заголовок "Добавить студентов:"')),
                ('add_students_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Добавить студентов:"')),
                ('add_students_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Добавить студентов:"')),
                ('add_students_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Добавить студентов:"')),
                ('results', models.CharField(max_length=255, verbose_name='Заголовок "Результаты:"')),
                ('results_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Результаты:"')),
                ('results_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Результаты:"')),
                ('results_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок "Результаты:"')),
            ],
            options={
                'verbose_name': 'Заголовки ФКЖ',
                'verbose_name_plural': 'Заголовки ФКЖ',
            },
        ),
    ]
