# Generated by Django 5.2 on 2025-07-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0013_titlesfkj'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlesfkj',
            name='download_exel',
            field=models.CharField(default='Скачать Excel', max_length=255, verbose_name='Заголовок "Скачать Excel"'),
        ),
        migrations.AddField(
            model_name='titlesfkj',
            name='download_exel_en',
            field=models.CharField(default='Скачать Excel', max_length=255, null=True, verbose_name='Заголовок "Скачать Excel"'),
        ),
        migrations.AddField(
            model_name='titlesfkj',
            name='download_exel_ky',
            field=models.CharField(default='Скачать Excel', max_length=255, null=True, verbose_name='Заголовок "Скачать Excel"'),
        ),
        migrations.AddField(
            model_name='titlesfkj',
            name='download_exel_ru',
            field=models.CharField(default='Скачать Excel', max_length=255, null=True, verbose_name='Заголовок "Скачать Excel"'),
        ),
        migrations.AddField(
            model_name='titlesfkj',
            name='download_pdf',
            field=models.CharField(default='Скачать PDF', max_length=255, verbose_name='Заголовок "Скачать PDF"'),
        ),
        migrations.AddField(
            model_name='titlesfkj',
            name='download_pdf_en',
            field=models.CharField(default='Скачать PDF', max_length=255, null=True, verbose_name='Заголовок "Скачать PDF"'),
        ),
        migrations.AddField(
            model_name='titlesfkj',
            name='download_pdf_ky',
            field=models.CharField(default='Скачать PDF', max_length=255, null=True, verbose_name='Заголовок "Скачать PDF"'),
        ),
        migrations.AddField(
            model_name='titlesfkj',
            name='download_pdf_ru',
            field=models.CharField(default='Скачать PDF', max_length=255, null=True, verbose_name='Заголовок "Скачать PDF"'),
        ),
    ]
