# Generated by Django 5.2 on 2025-07-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0014_titlesfkj_download_exel_titlesfkj_download_exel_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlesfkj',
            name='add_students',
            field=models.CharField(default='Добавить студентов:', max_length=255, verbose_name='Заголовок "Добавить студентов:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='add_students_en',
            field=models.CharField(default='Добавить студентов:', max_length=255, null=True, verbose_name='Заголовок "Добавить студентов:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='add_students_ky',
            field=models.CharField(default='Добавить студентов:', max_length=255, null=True, verbose_name='Заголовок "Добавить студентов:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='add_students_ru',
            field=models.CharField(default='Добавить студентов:', max_length=255, null=True, verbose_name='Заголовок "Добавить студентов:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='opening_hours',
            field=models.CharField(default='Часы работы:', max_length=255, verbose_name='Заголовок "Часы работы:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='opening_hours_en',
            field=models.CharField(default='Часы работы:', max_length=255, null=True, verbose_name='Заголовок "Часы работы:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='opening_hours_ky',
            field=models.CharField(default='Часы работы:', max_length=255, null=True, verbose_name='Заголовок "Часы работы:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='opening_hours_ru',
            field=models.CharField(default='Часы работы:', max_length=255, null=True, verbose_name='Заголовок "Часы работы:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='period',
            field=models.CharField(default='Период:', max_length=255, verbose_name='Заголовок "Период:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='period_en',
            field=models.CharField(default='Период:', max_length=255, null=True, verbose_name='Заголовок "Период:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='period_ky',
            field=models.CharField(default='Период:', max_length=255, null=True, verbose_name='Заголовок "Период:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='period_ru',
            field=models.CharField(default='Период:', max_length=255, null=True, verbose_name='Заголовок "Период:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='results',
            field=models.CharField(default='Результаты:', max_length=255, verbose_name='Заголовок "Результаты:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='results_en',
            field=models.CharField(default='Результаты:', max_length=255, null=True, verbose_name='Заголовок "Результаты:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='results_ky',
            field=models.CharField(default='Результаты:', max_length=255, null=True, verbose_name='Заголовок "Результаты:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='results_ru',
            field=models.CharField(default='Результаты:', max_length=255, null=True, verbose_name='Заголовок "Результаты:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='type_of_practice',
            field=models.CharField(default='Тип практики:', max_length=255, verbose_name='Заголовок "Тип практики:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='type_of_practice_en',
            field=models.CharField(default='Тип практики:', max_length=255, null=True, verbose_name='Заголовок "Тип практики:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='type_of_practice_ky',
            field=models.CharField(default='Тип практики:', max_length=255, null=True, verbose_name='Заголовок "Тип практики:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='type_of_practice_ru',
            field=models.CharField(default='Тип практики:', max_length=255, null=True, verbose_name='Заголовок "Тип практики:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='working_days',
            field=models.CharField(default='Рабочие дни:', max_length=255, verbose_name='Заголовок "Рабочие дни:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='working_days_en',
            field=models.CharField(default='Рабочие дни:', max_length=255, null=True, verbose_name='Заголовок "Рабочие дни:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='working_days_ky',
            field=models.CharField(default='Рабочие дни:', max_length=255, null=True, verbose_name='Заголовок "Рабочие дни:"'),
        ),
        migrations.AlterField(
            model_name='titlesfkj',
            name='working_days_ru',
            field=models.CharField(default='Рабочие дни:', max_length=255, null=True, verbose_name='Заголовок "Рабочие дни:"'),
        ),
    ]
