# Generated by Django 5.2 on 2025-07-18 10:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0015_alter_titlesfkj_add_students_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс'), (5, '5 курс'), (6, '6 курс'), (7, '7 курс')], null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='practices', to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
    ]
