# Generated by Django 5.2 on 2025-07-21 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0016_alter_practice_course_alter_practice_students'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='students',
            field=models.ManyToManyField(limit_choices_to={'role': 'student'}, related_name='practices', to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
    ]
