# Generated by Django 5.2 on 2025-07-23 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0017_alter_practice_students'),
        ('SuperAdmin', '0012_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_lessons', to='SuperAdmin.language', verbose_name='Язык обучения'),
        ),
    ]
