# Generated by Django 5.2 on 2025-07-23 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FKJ', '0018_practice_language'),
        ('SuperAdmin', '0013_institution_fkj'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution_practices', to='SuperAdmin.institution', verbose_name='Учреждение'),
        ),
    ]
